spring:
  application:
    name: AiTools
  ai:
    ollama:
      embedding:
        model: nomic-embed-text
      base-url: http://localhost:11434 # ollama服务地址
      chat:
        model: deepseek-r1:7b
        options:
          temperature: 0.8 # 模型温度，影响模型生成结果的随机性，越小越稳定
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: qwen-max-lastest
  servlet:
    multipart:
      max-file-size: 104857600    #100MB
      max-request-size: 104857600 #100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_tools?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 123456
    virtual-host: /
    # 连接池配置
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
        default-requeue-rejected: false
    # 发布者确认
    publisher-confirm-type: correlated
    publisher-returns: true
    # 消息转换器配置
    template:
      mandatory: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.ght666.aiTools.entity.po
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: status
      logic-delete-value: 0
      logic-not-delete-value: 1

logging:
  level:
    org.springframework.ai: debug
    com.ght666.aiTools: debug

pdf:
  temp:
    path: /tmp/pdf_upload
  max-file-size: 52428800  # 50MB
  chunk-size: 1000
  timeout: 300000

elasticsearch:
  host: es_host
  port: 9200
  username: elastic
  password: password




